name: build-maven-project
run-name: Build maven project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'termurin'
          java-version: '21'
          cache: 'maven'
        name: Build with Maven
        run: mvn -B package --file pom.xml
  upload:
    runs-on: ubuntu-latest
    steps:
      uses: actions/upload-artifact@v4
      with:
        name: dynatech-artifact
        path: ${{github.workspace}}/target/DynaTech.jar

